public enum ConvertType {
    USD_TO_ARS_SELL,
    USD_TO_ARS_BUY,
    ARS_TO_USD_SELL,
    ARS_TO_USD_BUY,
    USD_TO_ARS_SELL_BLUE,
    USD_TO_ARS_BUY_BLUE,
    ARS_TO_USD_SELL_BLUE,
    ARS_TO_USD_BUY_BLUE,
    NONE
}